[plugin]
class = "io.samjs.plugins.init.codemodify.CodeModifyFunctionPlugin"

[[dependency]]
path = "./lib/init-function-code-modify-compiler-plugin-1.0.0.jar"

[[dependency]]
path = "./lib/diagnostic-utils-lib-1.0.0.jar"
